name: 'Bump unRob/formulas formula'
description: 'bumps the version and shasums for a unRob/homebrew-formulas formula'
inputs:
  formula:
    description: 'the name of the formula to bump'
    required: true
  version:
    description: 'the version to bump the formula to'
    default: 'latest'
secrets:
  token:
    description: 'a personal access token to trigger the remote repo workflow with'
    required: true
runs:
  using: "composite"
  steps:
    - name: Trigger version bump
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
        VERSION: ${{ inputs.version }}
        FORMULA: ${{ inputs.formula }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/unRob/homebrew-formulas/actions/workflows/version-bump.yml/dispatches \
          -d '{"ref":"main","inputs":{ "formula": "Formula/'"$FORMULA"'.rb", "version": "'"$VERSION"'" }}'
