name: version-bump
on:
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula to update'
        required: true
        type: string
      version:
        description: 'Version to update to'
        default: latest
        type: string
run-name: Bump ${{ inputs.formula }} to ${{ inputs.version }}
jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: version-bump
        run: |
          git config user.name formulas-release-workflow
          git config user.email formula-release-workflow@un.rob.mx
          curl -L https://milpa.dev/install.sh | bash -
          milpa version-bump "$FORMULA" "$VERSION"
        env:
          FORMULA: ${{ inputs.formula }}
          VERSION: ${{ inputs.version }}
